# Generated by Django 5.2.3 on 2025-06-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_quotationrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="iban",
            field=models.CharField(blank=True, max_length=23, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="swift_code",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="supplier",
            name="trade_license_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="trn",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="vat_certificate",
            field=models.FileField(blank=True, upload_to="vat_docs/"),
        ),
        migrations.CreateModel(
            name="SupplierOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to="purchasing.supplier",
                    ),
                ),
            ],
        ),
    ]
