# Generated by Django 5.2.3 on 2025-06-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_remove_supplier_contact_info_supplier_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("swift_code", models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="swift_code",
        ),
        migrations.AddField(
            model_name="supplier",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchasing.bank",
            ),
        ),
    ]
