# Generated by Django 5.2.3 on 2025-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0005_add_bank_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
