# Generated by Django 5.2.3 on 2025-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0008_payment_status_purchaseorder_acknowledged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisition",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
