# Generated by Django 5.2.3 on 2025-06-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_migrate_skus"),
        ("purchasing", "0009_add_items_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisition",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_reqs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisition",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Product", "Product"),
                    ("Service", "Service"),
                    ("Office Supply", "Office Supply"),
                    ("Other", "Other"),
                ],
                default="Product",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
