from django.urls import path
from . import views

urlpatterns = [
    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/add/', views.SupplierCreateView.as_view(), name='supplier_add'),
    path('suppliers/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    path('suppliers/<int:pk>/edit/', views.SupplierUpdateView.as_view(), name='supplier_edit'),
    path('suppliers/<int:pk>/toggle/', views.SupplierToggleView.as_view(), name='supplier_toggle'),
    path('suppliers/<int:pk>/verify/', views.SupplierVerifyView.as_view(), name='supplier_verify'),
    path('suppliers/<int:pk>/request-otp/', views.SupplierRequestOTPView.as_view(), name='supplier_request_otp'),
    path('purchase-orders/add/', views.PurchaseOrderCreateView.as_view(), name='purchase_order_add'),
    path('purchase-orders/<int:pk>/', views.PurchaseOrderDetailView.as_view(), name='purchase_order_detail'),
    path('purchase-orders/<int:pk>/ack/', views.PurchaseOrderAcknowledgeView.as_view(), name='purchase_order_ack'),
    path('purchase-orders/<int:po_id>/lines/<int:line_id>/receive/', views.GoodsReceiptCreateView.as_view(), name='goods_receipt_add'),
    path('quotations/add/', views.QuotationRequestCreateView.as_view(), name='quotation_add'),
    path('quotations/compare/', views.QuotationComparisonView.as_view(), name='quotation_compare'),
    path('quotations/<int:line_id>/select/', views.QuotationSelectView.as_view(), name='quotation_select'),
    path('invoices/', views.SupplierInvoiceListView.as_view(), name='invoice_list'),
    path('invoices/add/', views.SupplierInvoiceCreateView.as_view(), name='invoice_add'),
    path('invoices/<int:pk>/match/', views.InvoiceMatchView.as_view(), name='invoice_match'),
    path('payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('payments/add/', views.PaymentCreateView.as_view(), name='payment_add'),
    path('payments/<int:pk>/approve/', views.PaymentApprovalView.as_view(), name='payment_approve'),
    path('requisitions/', views.PurchaseRequisitionListView.as_view(), name='requisition_list'),
    path('requisitions/add/', views.PurchaseRequisitionCreateView.as_view(), name='requisition_add'),
    path('requisitions/<int:pk>/', views.PurchaseRequisitionDetailView.as_view(), name='requisition_detail'),
    path('requisitions/<int:pk>/approve/', views.PurchaseRequisitionApproveView.as_view(), name='requisition_approve'),
    path('requisitions/<int:pk>/pdf/', views.PurchaseRequisitionPDFView.as_view(), name='requisition_pdf'),
    path('suppliers/<int:supplier_id>/evaluate/', views.SupplierEvaluationCreateView.as_view(), name='supplier_evaluate'),
    path('banks/search/', views.BankSearchView.as_view(), name='bank_search'),
    path('services/search/', views.ServiceItemSearchView.as_view(), name='service_search'),
    path('office-supplies/search/', views.OfficeSupplyItemSearchView.as_view(), name='office_supply_search'),
    path('assets/search/', views.AssetItemSearchView.as_view(), name='asset_item_search'),
    path('it-software/search/', views.ITSoftwareItemSearchView.as_view(), name='it_item_search'),

    path('services/', views.ServiceItemListView.as_view(), name='service_list'),
    path('services/add/', views.ServiceItemCreateView.as_view(), name='service_add'),
    path('services/<int:pk>/edit/', views.ServiceItemUpdateView.as_view(), name='service_edit'),
    path('services/<int:pk>/delete/', views.ServiceItemDeleteView.as_view(), name='service_delete'),

    path('office-supplies/', views.OfficeSupplyItemListView.as_view(), name='office_supply_list'),
    path('office-supplies/add/', views.OfficeSupplyItemCreateView.as_view(), name='office_supply_add'),
    path('office-supplies/<int:pk>/edit/', views.OfficeSupplyItemUpdateView.as_view(), name='office_supply_edit'),
    path('office-supplies/<int:pk>/delete/', views.OfficeSupplyItemDeleteView.as_view(), name='office_supply_delete'),

    path('assets/', views.AssetItemListView.as_view(), name='asset_item_list'),
    path('assets/add/', views.AssetItemCreateView.as_view(), name='asset_item_add'),
    path('assets/<int:pk>/edit/', views.AssetItemUpdateView.as_view(), name='asset_item_edit'),
    path('assets/<int:pk>/delete/', views.AssetItemDeleteView.as_view(), name='asset_item_delete'),

    path('it-software/', views.ITSoftwareItemListView.as_view(), name='it_item_list'),
    path('it-software/add/', views.ITSoftwareItemCreateView.as_view(), name='it_item_add'),
    path('it-software/<int:pk>/edit/', views.ITSoftwareItemUpdateView.as_view(), name='it_item_edit'),
    path('it-software/<int:pk>/delete/', views.ITSoftwareItemDeleteView.as_view(), name='it_item_delete'),
]
