from django.urls import path
from . import views

urlpatterns = [
    path('suppliers/', views.SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/add/', views.SupplierCreateView.as_view(), name='supplier_add'),
    path('suppliers/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier_detail'),
    path('suppliers/<int:pk>/edit/', views.SupplierUpdateView.as_view(), name='supplier_edit'),
    path('suppliers/<int:pk>/toggle/', views.SupplierToggleView.as_view(), name='supplier_toggle'),
    path('suppliers/<int:pk>/verify/', views.SupplierVerifyView.as_view(), name='supplier_verify'),
    path('suppliers/<int:pk>/request-otp/', views.SupplierRequestOTPView.as_view(), name='supplier_request_otp'),
    path('purchase-orders/add/', views.PurchaseOrderCreateView.as_view(), name='purchase_order_add'),
    path('purchase-orders/<int:pk>/', views.PurchaseOrderDetailView.as_view(), name='purchase_order_detail'),
    path('purchase-orders/<int:pk>/ack/', views.PurchaseOrderAcknowledgeView.as_view(), name='purchase_order_ack'),
    path('purchase-orders/<int:po_id>/lines/<int:line_id>/receive/', views.GoodsReceiptCreateView.as_view(), name='goods_receipt_add'),
    path('quotations/add/', views.QuotationRequestCreateView.as_view(), name='quotation_add'),
    path('quotations/compare/', views.QuotationComparisonView.as_view(), name='quotation_compare'),
    path('quotations/<int:line_id>/select/', views.QuotationSelectView.as_view(), name='quotation_select'),
    path('invoices/', views.SupplierInvoiceListView.as_view(), name='invoice_list'),
    path('invoices/add/', views.SupplierInvoiceCreateView.as_view(), name='invoice_add'),
    path('invoices/<int:pk>/match/', views.InvoiceMatchView.as_view(), name='invoice_match'),
    path('payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('payments/add/', views.PaymentCreateView.as_view(), name='payment_add'),
    path('payments/<int:pk>/approve/', views.PaymentApprovalView.as_view(), name='payment_approve'),
    path('requisitions/', views.PurchaseRequisitionListView.as_view(), name='requisition_list'),
    path('requisitions/add/', views.PurchaseRequisitionCreateView.as_view(), name='requisition_add'),
    path('requisitions/<int:pk>/', views.PurchaseRequisitionDetailView.as_view(), name='requisition_detail'),
    path('requisitions/<int:pk>/approve/', views.PurchaseRequisitionApproveView.as_view(), name='requisition_approve'),
    path('requisitions/<int:pk>/pdf/', views.PurchaseRequisitionPDFView.as_view(), name='requisition_pdf'),
    path('suppliers/<int:supplier_id>/evaluate/', views.SupplierEvaluationCreateView.as_view(), name='supplier_evaluate'),
    path('banks/search/', views.BankSearchView.as_view(), name='bank_search'),
]
