# Generated by Django 5.2.3 on 2025-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_profile_picture"),
        ("inventory", "0002_productunit_product_inventoryadjustment_stocklot_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("name", "company"), name="unique_category_per_company"
            ),
        ),
    ]
