# Generated by Django 5.2.3 on 2025-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_add_category_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discontinued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_discontinued",
            field=models.BooleanField(default=False),
        ),
    ]
