# Generated by Django 5.2.3 on 2025-06-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_discontinued_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentifierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="track_serial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="required_identifiers",
            field=models.ManyToManyField(blank=True, to="inventory.identifiertype"),
        ),
        migrations.CreateModel(
            name="ProductSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=100)),
                ("is_sold", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "serial")},
            },
        ),
    ]
