# Generated by Django 5.2.3 on 2025-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_identifiertype_product_track_serial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
