# Generated by Django 5.2.3 on 2025-06-24 08:54

from django.db import migrations, models
import random
import string


def fill_category_codes(apps, schema_editor):
    Category = apps.get_model('inventory', 'ProductCategory')
    for cat in Category.objects.filter(code=''):
        for length in range(4, 9):
            for _ in range(100):
                code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))
                if not Category.objects.filter(code=code).exists():
                    cat.code = code
                    cat.save(update_fields=['code'])
                    break
            if cat.code:
                break



class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_product_specs_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="legacy_sku",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="code",
            field=models.CharField(default="", blank=True, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.RunPython(fill_category_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productcategory",
            name="code",
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
