# Generated by Django 5.2.3 on 2025-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
