# Generated by Django 5.2.3 on 2025-06-24 08:53

from django.db import migrations, models
import random
import string


def fill_codes(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    for company in Company.objects.filter(code=''):
        prefix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
        seq = 1
        while True:
            code = f"{prefix}{seq:02d}"
            if not Company.objects.filter(code=code).exists():
                company.code = code
                company.save(update_fields=['code'])
                break
            seq += 1


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.RunPython(fill_codes, reverse_code=migrations.RunPython.noop),
    ]
